export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  pricePerUnit: number;
  unit: string;
  stockQuantity: number;
  minOrderQuantity: number;
  imageUrl: string;
  category: string;
  categorySlug: string;
  farmerName: string;
  farmName: string;
  farmLocation: string;
  farmerAvatar: string;
  farmerRating: number;
  isOrganic: boolean;
  harvestDate: string;
  expiryDate: string;
  viewCount: number;
  orderCount: number;
  tags: string[];
  createdAt: string;
}

export const categories = [
  { name: "Vegetables", slug: "vegetables", icon: "🥬", count: 24 },
  { name: "Fruits", slug: "fruits", icon: "🍌", count: 18 },
  { name: "Grains & Rice", slug: "grains-rice", icon: "🌾", count: 12 },
  { name: "Root Crops", slug: "root-crops", icon: "🥔", count: 9 },
  { name: "Herbs & Spices", slug: "herbs-spices", icon: "🌿", count: 15 },
  { name: "Poultry & Eggs", slug: "poultry-eggs", icon: "🥚", count: 7 },
  { name: "Dairy", slug: "dairy", icon: "🥛", count: 5 },
  { name: "Seafood", slug: "seafood", icon: "🐟", count: 11 },
];

export const mockProducts: MockProduct[] = [
  {
    id: "prod-001",
    name: "Fresh Calamansi",
    slug: "fresh-calamansi",
    description: "Freshly harvested calamansi from our organic farm in Batangas. Perfect for juices, cooking, and condiments. Harvested at peak ripeness for the best flavor.",
    pricePerUnit: 80,
    unit: "kg",
    stockQuantity: 500,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Juan dela Cruz",
    farmName: "Dela Cruz Organic Farm",
    farmLocation: "Lipa, Batangas",
    farmerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    farmerRating: 4.8,
    isOrganic: true,
    harvestDate: "2024-01-10",
    expiryDate: "2024-01-25",
    viewCount: 342,
    orderCount: 56,
    tags: ["organic", "citrus", "fresh"],
    createdAt: "2024-01-05",
  },
  {
    id: "prod-002",
    name: "Benguet Strawberries",
    slug: "benguet-strawberries",
    description: "Sweet and juicy strawberries grown in the cool highlands of La Trinidad, Benguet. Hand-picked for quality and freshness.",
    pricePerUnit: 350,
    unit: "kg",
    stockQuantity: 200,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Maria Santos",
    farmName: "Highland Berry Farm",
    farmLocation: "La Trinidad, Benguet",
    farmerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    farmerRating: 4.9,
    isOrganic: true,
    harvestDate: "2024-01-12",
    expiryDate: "2024-01-20",
    viewCount: 891,
    orderCount: 124,
    tags: ["organic", "highland", "premium"],
    createdAt: "2024-01-08",
  },
  {
    id: "prod-003",
    name: "Nueva Ecija Rice (Sinandomeng)",
    slug: "nueva-ecija-rice-sinandomeng",
    description: "Premium Sinandomeng rice from the rice granary of the Philippines. Soft, aromatic, and perfect for everyday meals.",
    pricePerUnit: 55,
    unit: "kg",
    stockQuantity: 2000,
    minOrderQuantity: 25,
    imageUrl: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600",
    category: "Grains & Rice",
    categorySlug: "grains-rice",
    farmerName: "Pedro Reyes",
    farmName: "Reyes Rice Mill",
    farmLocation: "Cabanatuan, Nueva Ecija",
    farmerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2024-01-01",
    expiryDate: "2024-06-01",
    viewCount: 1205,
    orderCount: 312,
    tags: ["staple", "premium", "aromatic"],
    createdAt: "2024-01-02",
  },
  {
    id: "prod-004",
    name: "Baguio Lettuce",
    slug: "baguio-lettuce",
    description: "Crisp and fresh lettuce varieties grown in the cool climate of Baguio City. Includes romaine, butterhead, and iceberg varieties.",
    pricePerUnit: 120,
    unit: "kg",
    stockQuantity: 300,
    minOrderQuantity: 3,
    imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600",
    category: "Vegetables",
    categorySlug: "vegetables",
    farmerName: "Rosa Mendoza",
    farmName: "Mendoza Highland Greens",
    farmLocation: "Baguio City, Benguet",
    farmerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    farmerRating: 4.6,
    isOrganic: true,
    harvestDate: "2024-01-13",
    expiryDate: "2024-01-18",
    viewCount: 567,
    orderCount: 89,
    tags: ["organic", "highland", "salad"],
    createdAt: "2024-01-10",
  },
  {
    id: "prod-005",
    name: "Free-Range Eggs",
    slug: "free-range-eggs",
    description: "Fresh free-range eggs from happy chickens in Pampanga. Rich yolks and superior taste compared to commercial eggs.",
    pricePerUnit: 12,
    unit: "piece",
    stockQuantity: 1000,
    minOrderQuantity: 30,
    imageUrl: "https://images.unsplash.com/photo-1569288052389-dac9b01c9c05?w=600",
    category: "Poultry & Eggs",
    categorySlug: "poultry-eggs",
    farmerName: "Antonio Garcia",
    farmName: "Garcia Free-Range Poultry",
    farmLocation: "San Fernando, Pampanga",
    farmerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    farmerRating: 4.5,
    isOrganic: false,
    harvestDate: "2024-01-14",
    expiryDate: "2024-02-14",
    viewCount: 423,
    orderCount: 201,
    tags: ["free-range", "fresh", "protein"],
    createdAt: "2024-01-11",
  },
  {
    id: "prod-006",
    name: "Laguna Purple Yam (Ube)",
    slug: "laguna-purple-yam-ube",
    description: "Premium purple yam (ube) from Laguna, perfect for making halaya, ice cream, and other Filipino desserts. Deep purple color guaranteed.",
    pricePerUnit: 150,
    unit: "kg",
    stockQuantity: 400,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1546470427-0d62b9f43b2a?w=600",
    category: "Root Crops",
    categorySlug: "root-crops",
    farmerName: "Elena Villanueva",
    farmName: "Villanueva Root Crops Farm",
    farmLocation: "Los Baños, Laguna",
    farmerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100",
    farmerRating: 4.8,
    isOrganic: false,
    harvestDate: "2024-01-08",
    expiryDate: "2024-03-08",
    viewCount: 678,
    orderCount: 145,
    tags: ["dessert", "premium", "filipino-staple"],
    createdAt: "2024-01-06",
  },
  {
    id: "prod-007",
    name: "Fresh Basil (Balanoi)",
    slug: "fresh-basil-balanoi",
    description: "Aromatic fresh basil grown in our herb garden in Tagaytay. Perfect for Italian dishes, Thai cuisine, and garnishing.",
    pricePerUnit: 200,
    unit: "kg",
    stockQuantity: 50,
    minOrderQuantity: 1,
    imageUrl: "https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600",
    category: "Herbs & Spices",
    categorySlug: "herbs-spices",
    farmerName: "Carlos Aquino",
    farmName: "Aquino Herb Garden",
    farmLocation: "Tagaytay, Cavite",
    farmerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    farmerRating: 4.4,
    isOrganic: true,
    harvestDate: "2024-01-14",
    expiryDate: "2024-01-19",
    viewCount: 234,
    orderCount: 45,
    tags: ["organic", "aromatic", "culinary"],
    createdAt: "2024-01-12",
  },
  {
    id: "prod-008",
    name: "Fresh Bangus (Milkfish)",
    slug: "fresh-bangus-milkfish",
    description: "Premium boneless bangus from Dagupan fish farms. Cleaned, deboned, and vacuum-sealed for freshness. The national fish of the Philippines.",
    pricePerUnit: 280,
    unit: "kg",
    stockQuantity: 150,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
    category: "Seafood",
    categorySlug: "seafood",
    farmerName: "Roberto Pangasinan",
    farmName: "Pangasinan Fish Farm",
    farmLocation: "Dagupan, Pangasinan",
    farmerAvatar: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2024-01-14",
    expiryDate: "2024-01-17",
    viewCount: 890,
    orderCount: 234,
    tags: ["seafood", "boneless", "premium"],
    createdAt: "2024-01-13",
  },
];
