export interface MockProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  pricePerUnit: number;
  unit: string;
  stockQuantity: number;
  minOrderQuantity: number;
  imageUrl: string;
  category: string;
  categorySlug: string;
  farmerName: string;
  farmName: string;
  farmLocation: string;
  farmerAvatar: string;
  farmerRating: number;
  isOrganic: boolean;
  harvestDate: string;
  expiryDate: string;
  viewCount: number;
  orderCount: number;
  tags: string[];
  createdAt: string;
}

export const categories = [
  { name: "Vegetables", slug: "vegetables", icon: "🥬", count: 24 },
  { name: "Fruits", slug: "fruits", icon: "🍌", count: 18 },
  { name: "Grains & Rice", slug: "grains-rice", icon: "🌾", count: 12 },
  { name: "Root Crops", slug: "root-crops", icon: "🥔", count: 9 },
  { name: "Herbs & Spices", slug: "herbs-spices", icon: "🌿", count: 15 },
  { name: "Poultry & Eggs", slug: "poultry-eggs", icon: "🥚", count: 7 },
  { name: "Dairy", slug: "dairy", icon: "🥛", count: 5 },
  { name: "Seafood", slug: "seafood", icon: "🐟", count: 11 },
];

export const mockProducts: MockProduct[] = [
  {
    id: "prod-001",
    name: "Fresh Calamansi",
    slug: "fresh-calamansi",
    description: "Freshly harvested calamansi from our organic farm in Batangas. Perfect for juices, cooking, and condiments. Harvested at peak ripeness for the best flavor.",
    pricePerUnit: 80,
    unit: "kg",
    stockQuantity: 500,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Juan dela Cruz",
    farmName: "Dela Cruz Organic Farm",
    farmLocation: "Lipa, Batangas",
    farmerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100",
    farmerRating: 4.8,
    isOrganic: true,
    harvestDate: "2026-07-18",
    expiryDate: "2026-08-15",
    viewCount: 342,
    orderCount: 56,
    tags: ["organic", "citrus", "fresh"],
    createdAt: "2026-07-15",
  },
  {
    id: "prod-002",
    name: "Benguet Strawberries",
    slug: "benguet-strawberries",
    description: "Sweet and juicy strawberries grown in the cool highlands of La Trinidad, Benguet. Hand-picked for quality and freshness.",
    pricePerUnit: 350,
    unit: "kg",
    stockQuantity: 200,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Maria Santos",
    farmName: "Highland Berry Farm",
    farmLocation: "La Trinidad, Benguet",
    farmerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100",
    farmerRating: 4.9,
    isOrganic: true,
    harvestDate: "2026-07-19",
    expiryDate: "2026-08-02",
    viewCount: 891,
    orderCount: 124,
    tags: ["organic", "highland", "premium"],
    createdAt: "2026-07-17",
  },
  {
    id: "prod-003",
    name: "Nueva Ecija Rice (Sinandomeng)",
    slug: "nueva-ecija-rice-sinandomeng",
    description: "Premium Sinandomeng rice from the rice granary of the Philippines. Soft, aromatic, and perfect for everyday meals.",
    pricePerUnit: 55,
    unit: "kg",
    stockQuantity: 2000,
    minOrderQuantity: 25,
    imageUrl: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=600",
    category: "Grains & Rice",
    categorySlug: "grains-rice",
    farmerName: "Pedro Reyes",
    farmName: "Reyes Rice Mill",
    farmLocation: "Cabanatuan, Nueva Ecija",
    farmerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2026-07-10",
    expiryDate: "2027-01-10",
    viewCount: 1205,
    orderCount: 312,
    tags: ["staple", "premium", "aromatic"],
    createdAt: "2026-07-12",
  },
  {
    id: "prod-004",
    name: "Baguio Lettuce",
    slug: "baguio-lettuce",
    description: "Crisp and fresh lettuce varieties grown in the cool climate of Baguio City. Includes romaine, butterhead, and iceberg varieties.",
    pricePerUnit: 120,
    unit: "kg",
    stockQuantity: 300,
    minOrderQuantity: 3,
    imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600",
    category: "Vegetables",
    categorySlug: "vegetables",
    farmerName: "Rosa Mendoza",
    farmName: "Mendoza Highland Greens",
    farmLocation: "Baguio City, Benguet",
    farmerAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100",
    farmerRating: 4.6,
    isOrganic: true,
    harvestDate: "2026-07-20",
    expiryDate: "2026-08-05",
    viewCount: 567,
    orderCount: 89,
    tags: ["organic", "highland", "salad"],
    createdAt: "2026-07-18",
  },
  {
    id: "prod-005",
    name: "Free-Range Eggs",
    slug: "free-range-eggs",
    description: "Fresh free-range eggs from happy chickens in Pampanga. Rich yolks and superior taste compared to commercial eggs.",
    pricePerUnit: 12,
    unit: "piece",
    stockQuantity: 1000,
    minOrderQuantity: 30,
    imageUrl: "https://images.unsplash.com/photo-1569288052389-dac9b01c9c05?w=600",
    category: "Poultry & Eggs",
    categorySlug: "poultry-eggs",
    farmerName: "Antonio Garcia",
    farmName: "Garcia Free-Range Poultry",
    farmLocation: "San Fernando, Pampanga",
    farmerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100",
    farmerRating: 4.5,
    isOrganic: false,
    harvestDate: "2026-07-21",
    expiryDate: "2026-08-21",
    viewCount: 423,
    orderCount: 201,
    tags: ["free-range", "fresh", "protein"],
    createdAt: "2026-07-19",
  },
  {
    id: "prod-006",
    name: "Laguna Purple Yam (Ube)",
    slug: "laguna-purple-yam-ube",
    description: "Premium purple yam (ube) from Laguna, perfect for making halaya, ice cream, and other Filipino desserts. Deep purple color guaranteed.",
    pricePerUnit: 150,
    unit: "kg",
    stockQuantity: 400,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1546470427-0d62b9f43b2a?w=600",
    category: "Root Crops",
    categorySlug: "root-crops",
    farmerName: "Elena Villanueva",
    farmName: "Villanueva Root Crops Farm",
    farmLocation: "Los Banos, Laguna",
    farmerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100",
    farmerRating: 4.8,
    isOrganic: false,
    harvestDate: "2026-07-15",
    expiryDate: "2026-09-15",
    viewCount: 678,
    orderCount: 145,
    tags: ["dessert", "premium", "filipino-staple"],
    createdAt: "2026-07-14",
  },
  {
    id: "prod-007",
    name: "Fresh Basil (Balanoi)",
    slug: "fresh-basil-balanoi",
    description: "Aromatic fresh basil grown in our herb garden in Tagaytay. Perfect for Italian dishes, Thai cuisine, and garnishing.",
    pricePerUnit: 200,
    unit: "kg",
    stockQuantity: 50,
    minOrderQuantity: 1,
    imageUrl: "https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600",
    category: "Herbs & Spices",
    categorySlug: "herbs-spices",
    farmerName: "Carlos Aquino",
    farmName: "Aquino Herb Garden",
    farmLocation: "Tagaytay, Cavite",
    farmerAvatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100",
    farmerRating: 4.4,
    isOrganic: true,
    harvestDate: "2026-07-20",
    expiryDate: "2026-08-10",
    viewCount: 234,
    orderCount: 45,
    tags: ["organic", "aromatic", "culinary"],
    createdAt: "2026-07-19",
  },
  {
    id: "prod-008",
    name: "Fresh Bangus (Milkfish)",
    slug: "fresh-bangus-milkfish",
    description: "Premium boneless bangus from Dagupan fish farms. Cleaned, deboned, and vacuum-sealed for freshness. The national fish of the Philippines.",
    pricePerUnit: 280,
    unit: "kg",
    stockQuantity: 150,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600",
    category: "Seafood",
    categorySlug: "seafood",
    farmerName: "Roberto Pangasinan",
    farmName: "Pangasinan Fish Farm",
    farmLocation: "Dagupan, Pangasinan",
    farmerAvatar: "https://images.unsplash.com/photo-1552058544-f2b08422138a?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2026-07-21",
    expiryDate: "2026-08-05",
    viewCount: 890,
    orderCount: 234,
    tags: ["seafood", "boneless", "premium"],
    createdAt: "2026-07-20",
  },
  {
    id: "prod-009",
    name: "Organic Kangkong (Water Spinach)",
    slug: "organic-kangkong",
    description: "Fresh organic kangkong harvested daily from our aquaponics farm. Tender stems and leaves, perfect for adobo and sinigang.",
    pricePerUnit: 60,
    unit: "kg",
    stockQuantity: 200,
    minOrderQuantity: 3,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600",
    category: "Vegetables",
    categorySlug: "vegetables",
    farmerName: "Lorna Bautista",
    farmName: "Bautista Aquaponics",
    farmLocation: "Tarlac City, Tarlac",
    farmerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100",
    farmerRating: 4.6,
    isOrganic: true,
    harvestDate: "2026-07-21",
    expiryDate: "2026-08-01",
    viewCount: 312,
    orderCount: 78,
    tags: ["organic", "leafy-green", "daily-harvest"],
    createdAt: "2026-07-20",
  },
  {
    id: "prod-010",
    name: "Davao Carabao Mango",
    slug: "davao-carabao-mango",
    description: "Sweet and fiberless Carabao mangoes from Davao. Export quality, handpicked at optimal ripeness. The sweetest mangoes in the world.",
    pricePerUnit: 180,
    unit: "kg",
    stockQuantity: 800,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Danny Mindanao",
    farmName: "Mindanao Mango Plantation",
    farmLocation: "Davao City, Davao del Sur",
    farmerAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100",
    farmerRating: 4.9,
    isOrganic: false,
    harvestDate: "2026-07-18",
    expiryDate: "2026-08-08",
    viewCount: 1450,
    orderCount: 289,
    tags: ["export-quality", "sweet", "premium"],
    createdAt: "2026-07-16",
  },
  {
    id: "prod-011",
    name: "Fresh Ginger (Luya)",
    slug: "fresh-ginger-luya",
    description: "Organically grown ginger from the highlands of Bukidnon. Strong aroma and spicy flavor, perfect for salabat, cooking, and traditional medicine.",
    pricePerUnit: 140,
    unit: "kg",
    stockQuantity: 300,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1615485500710-aa71860d4026?w=600",
    category: "Herbs & Spices",
    categorySlug: "herbs-spices",
    farmerName: "Ramon Bukidnon",
    farmName: "Bukidnon Highland Spices",
    farmLocation: "Malaybalay, Bukidnon",
    farmerAvatar: "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100",
    farmerRating: 4.5,
    isOrganic: true,
    harvestDate: "2026-07-19",
    expiryDate: "2026-09-19",
    viewCount: 245,
    orderCount: 67,
    tags: ["organic", "medicinal", "spicy"],
    createdAt: "2026-07-18",
  },
  {
    id: "prod-012",
    name: "Quezon Coconut (Buko)",
    slug: "quezon-coconut-buko",
    description: "Young coconuts from the coconut capital of the Philippines. Sweet buko juice and tender meat. Freshly harvested and delivered same day.",
    pricePerUnit: 35,
    unit: "piece",
    stockQuantity: 500,
    minOrderQuantity: 10,
    imageUrl: "https://images.unsplash.com/photo-1550828520-4cb496926fc9?w=600",
    category: "Fruits",
    categorySlug: "fruits",
    farmerName: "Nena Quezon",
    farmName: "Quezon Coco Farm",
    farmLocation: "Lucban, Quezon",
    farmerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2026-07-21",
    expiryDate: "2026-08-10",
    viewCount: 520,
    orderCount: 156,
    tags: ["fresh", "young-coconut", "same-day"],
    createdAt: "2026-07-20",
  },
  {
    id: "prod-013",
    name: "Ilocos Garlic",
    slug: "ilocos-garlic",
    description: "Native Ilocos garlic known for its strong flavor and aroma. Smaller but more potent than imported varieties. Sun-dried for maximum shelf life.",
    pricePerUnit: 250,
    unit: "kg",
    stockQuantity: 150,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1540148426945-6cf22a6b2571?w=600",
    category: "Herbs & Spices",
    categorySlug: "herbs-spices",
    farmerName: "Manuel Ilocano",
    farmName: "Ilocano Heritage Farm",
    farmLocation: "Vigan, Ilocos Sur",
    farmerAvatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=100",
    farmerRating: 4.8,
    isOrganic: false,
    harvestDate: "2026-07-10",
    expiryDate: "2026-10-10",
    viewCount: 378,
    orderCount: 112,
    tags: ["native", "aromatic", "long-shelf-life"],
    createdAt: "2026-07-11",
  },
  {
    id: "prod-014",
    name: "Fresh Carabao Milk",
    slug: "fresh-carabao-milk",
    description: "Pure carabao milk from our dairy farm in Nueva Ecija. Rich, creamy, and perfect for making pastillas, kesong puti, and other dairy products.",
    pricePerUnit: 95,
    unit: "liter",
    stockQuantity: 80,
    minOrderQuantity: 5,
    imageUrl: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600",
    category: "Dairy",
    categorySlug: "dairy",
    farmerName: "Linda Nueva",
    farmName: "Nueva Ecija Dairy Cooperative",
    farmLocation: "Muñoz, Nueva Ecija",
    farmerAvatar: "https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=100",
    farmerRating: 4.6,
    isOrganic: false,
    harvestDate: "2026-07-21",
    expiryDate: "2026-07-28",
    viewCount: 189,
    orderCount: 45,
    tags: ["fresh", "creamy", "artisan"],
    createdAt: "2026-07-21",
  },
  {
    id: "prod-015",
    name: "Batangas Kapeng Barako",
    slug: "batangas-kapeng-barako",
    description: "Authentic Kapeng Barako beans from Lipa, Batangas. Bold, strong flavor with a distinctive aroma. Freshly roasted and ground to order.",
    pricePerUnit: 450,
    unit: "kg",
    stockQuantity: 100,
    minOrderQuantity: 1,
    imageUrl: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600",
    category: "Herbs & Spices",
    categorySlug: "herbs-spices",
    farmerName: "Jose Batangueño",
    farmName: "Batangas Coffee Estate",
    farmLocation: "Lipa, Batangas",
    farmerAvatar: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=100",
    farmerRating: 4.9,
    isOrganic: true,
    harvestDate: "2026-07-15",
    expiryDate: "2026-12-15",
    viewCount: 934,
    orderCount: 278,
    tags: ["coffee", "premium", "local-heritage"],
    createdAt: "2026-07-14",
  },
  {
    id: "prod-016",
    name: "Pampanga Sisig Meat (Pre-cut)",
    slug: "pampanga-sisig-meat",
    description: "Pre-cut pork belly and ears, perfect for making authentic Kapampangan sisig. Cleaned and ready to cook. From free-range pigs.",
    pricePerUnit: 320,
    unit: "kg",
    stockQuantity: 100,
    minOrderQuantity: 2,
    imageUrl: "https://images.unsplash.com/photo-1602473812169-caa80dad937e?w=600",
    category: "Poultry & Eggs",
    categorySlug: "poultry-eggs",
    farmerName: "Chef Pampanga",
    farmName: "Pampanga Meat Supply",
    farmLocation: "Angeles City, Pampanga",
    farmerAvatar: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=100",
    farmerRating: 4.7,
    isOrganic: false,
    harvestDate: "2026-07-21",
    expiryDate: "2026-07-28",
    viewCount: 456,
    orderCount: 189,
    tags: ["ready-to-cook", "premium", "kapampangan"],
    createdAt: "2026-07-20",
  },
];
